# File:"C:\Users\341510davu\OneDrive - OX2\3. Grid - SUMSF\1. Power System Studies\1. Main Test Environment\Git_SF_BESS_Summerville\PSSE_sim\base_model\SLDs_SUMSF\temp.py", generated on THU, FEB 01 2024  11:23, PSS(R)E release 34.05.01
psspy.machine_chng_2(273501,r"""1""",[_i,_i,_i,_i,_i,_i],[_f,_f,_f,_f, 92.0,-51.0,_f,_f,_f,_f,_f,_f,_f,_f,_f,_f,_f])
psspy.save(r"""C:\Users\341510davu\OneDrive - OX2\3. Grid - SUMSF\1. Power System Studies\1. Main Test Environment\Git_SF_BESS_Summerville\PSSE_sim\base_model\HighLoad\SUMSF_high_genon.sav""")
psspy.case(r"""C:\Users\341510davu\OneDrive - OX2\3. Grid - SUMSF\1. Power System Studies\1. Main Test Environment\Git_SF_BESS_Summerville\PSSE_sim\base_model\LowLoad\SUMSF_low_genon.sav""")
psspy.machine_chng_2(273501,r"""1""",[_i,_i,_i,_i,_i,_i],[ 91.0,_f,_f,_f, 92.0,-51.0,_f,_f,_f,_f,_f,_f,_f,_f,_f,_f,_f])
psspy.case(r"""C:\Users\341510davu\OneDrive - OX2\3. Grid - SUMSF\1. Power System Studies\1. Main Test Environment\Git_SF_BESS_Summerville\PSSE_sim\base_model\LowLoad\SUMSF_low_genon.sav""")
psspy.bsysinit(1)
psspy.bsyso(1,800009)
psspy.bsysinit(1)
psspy.bsyso(1,800009)
psspy.growdiagram_2(1,1,[r"""BU 800009"""],0.0,0.0,[0,0,0,0,0,0,0,0,0,0,0,0,0])
psspy.case(r"""C:\Users\341510davu\OneDrive - OX2\3. Grid - SUMSF\1. Power System Studies\1. Main Test Environment\Git_SF_BESS_Summerville\PSSE_sim\base_model\HighLoad\SUMSF_high_genon.sav""")
psspy.case(r"""C:\Users\341510davu\OneDrive - OX2\3. Grid - SUMSF\1. Power System Studies\0. Models\1. PSSE\NEM\3. Integrating SUM SF\LowLoad\Final\SUMSF_low_genon.sav""")
psspy.case(r"""C:\Users\341510davu\OneDrive - OX2\3. Grid - SUMSF\1. Power System Studies\1. Main Test Environment\Git_SF_BESS_Summerville\PSSE_sim\base_model\LowLoad\SUMSF_low_genon.sav""")
psspy.case(r"""C:\Users\341510davu\OneDrive - OX2\3. Grid - SUMSF\1. Power System Studies\0. Models\1. PSSE\NEM\3. Integrating SUM SF\LowLoad\Final\SUMSF_low_genon.sav""")
psspy.case(r"""C:\work\3. Grid - SUMSF\1. Power System Studies\1. Main Test Environment\Git_SF_BESS_Summerville\PSSE_sim\model_copies\20240201-114222_S52512_SS\con33\After_SUMSF_high_genon.sav""")
